### ISSUE TITLE
Pipeline file with no steps causes fatal error

### ISSUE THREAD

**Issue by dominics** [vital-software/monofo-buildkite-plugin#310]
```yaml
env:
  FOO: "bar"

monorepo:
  matches: true
```

This should be treated as if it had a `steps: []` entry present
