### ISSUE TITLE
`MONOFO_ARTIFACT_<NAME>_SKIP` is unusable for skipping only incremental builds

### ISSUE THREAD

**Issue by dominics** [vital-software/monofo-buildkite-plugin#358]
## Goal for original `_SKIP`

Say you have an artifact named `example.catar.caibx` and you're trying to do the classic "incremental build" pattern:

```yaml
monorepo:
  pure: true
  expects: dependency.catar.caibx
  produces: example.catar.caibx
  matches:
    - "some-path/**"

steps:
  - name: "Compile example archive"
    depends_on:
      - dependency
    commands:
      - do-the-compile
      - produce-example-file-list-to-cache  # produces example.list
    env:
      MONOFO_ARTIFACT_EXAMPLE_BUILD_ID: ${MONOFO_ARTIFACT_EXAMPLE_BUILD_ID:-$MONOFO_BASE_BUILD_ID}  # provides the place to get the base artifact for the incremental build from
      MONOFO_ARTIFACT_EXAMPLE_SOFT_FAIL: 1                                                             # says: don't worry if I can't get a base artifact for the incremental build
    plugins:
      - docker-compose#v3.9.0:
          run: node
      - vital-software/monofo#v4.0.0:
          download:
            - dependency.catar.caibx
            - example.catar.caibx   # pre-cache incremental build
          upload:
            example.catar.caibx:
              filesFrom: example.list
              null: true
```

The plan was to have `MONOFO_ARTIFACT_EXAMPLE_SKIP=1` cause _just_ the incremental build part of _this step_ to be skipped, so that the produced example was run on a "clean" checkout, rather than checkout + previous result.

## Why the current design isn't enough

- Practically, you want an environment variable you can set globally, on all steps in the build
- But if you set `MONOFO_ARTIFACT_EXAMPLE_SKIP=1`, any steps in other partial pipelines that want to _actually_ depend on the latest copy of the artifact will _also_ be skipped

## Suggested fix

For the incremental use-case, we can detect that the same dependency is being uploaded later in the current step. And the skip the artifact iff we are uploading it.

We should use an additional environment variable for this new behavior, to retain BC: suggest `MONOFO_ARTIFACT_EXAMPLE_SKIP_PRECACHE=1`
